# Generated by Django 5.1.6 on 2025-02-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_faq_alter_slider_options_alter_slider_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Данное поле заполняется автоматически', verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default='', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to='slider/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='Заголовок'),
        ),
    ]
